Dev
WildCodeSchool-2024-02/JS-lyon-0224-P2-holidays_planner pull request #68
Opened 2024-04-25 12:53 UTC by kna1703

PR dev to main, new pages FilterCountryYear, AboutUs

2024-04-25 15:23 UTC, wildmatthieu requested changes
Pas mal dans l'ensemble ! des petites retouches a faire ici et la

2024-04-25 15:23 UTC, wildmatthieu commented on client/src/components/FilterCountrYear/FilterCountryYear.jsx
> +          return view === "month" && holiday ? holiday.name : null;
expliciter la condition holiday
holiday === true ?
holiday === false ? 
holiday === bananeflambee ?

2024-04-25 15:23 UTC, wildmatthieu commented on client/src/components/FilterCountry/FilterCountry.jsx
> +    if (countryCode) {
expliciter la condition
contryCode === 17 ?
contryCode === machin ?

2024-04-25 15:23 UTC, wildmatthieu commented on client/src/components/HomePage/HomeBody.jsx
> +      <h1>FIND&nbsp; YOUR &nbsp; PUBLIC &nbsp; HOLIDAYS !</h1>
les &nbsp; sont vraiment nécessaires ? ça ne fonctionne pas simplement :
      `<h1>FIND  YOUR  PUBLIC   HOLIDAYS !</h1>`

2024-04-26 07:34 UTC, kna1703 commented on client/src/assets/Fonts/JosefinSans/JosefinSans-Italic-VariableFont_wght.ttf
Cette police a été supprimée dans dev

2024-04-26 07:36 UTC, Kana-Fujihira commented on client/src/components/Common/Header/Header.jsx
> +        <img src={logo} alt="logo lazy day" className={styles.logo} />
nous choisissons l'anglais

2024-04-26 08:22 UTC, Kana-Fujihira approved these changes
Checked

2024-04-26 08:23 UTC, Kana-Fujihira approved these changes
checked

2024-04-26 09:59 UTC, wildmatthieu requested changes

2024-04-26 09:59 UTC, wildmatthieu commented on client/src/components/FilterCountrYear/FilterCountryYear.jsx
> +          return view === "month" && holiday ? holiday.name : null;
condition `holiday` à expliciter :) 
`return view === "month" && holiday === false ? holiday.name : null;`
`return view === "month" && holiday === true ? holiday.name : null;`
`return view === "month" && holiday.length > 0 ? holiday.name : null;`
...

2024-04-26 13:53 UTC, Kana-Fujihira commented on client/src/components/FilterCountrYear/FilterCountryYear.jsx
> +          return view === "month" && holiday ? holiday.name : null;
résoudre le problèm et expliciter la condition

2024-04-29 10:37 UTC, closed without merging